### ISSUE TITLE
SmartNumber unused accuracy parameter

### ISSUE THREAD

**Issue by flokixdev** [mathematicator-core/numbers#11]
@janbarasek At this time we do not use accuracy Smart Number parameter anywhere because we don't lose precision anywhere. For integers, there is a rounding parameter. I think we can remove the "accuracy" parameter, however I am not sure how to solve the backwards compatibility because it is a first parameter. It would be nice to be able to simply use e.g. `new SmartNumber('15.12')` without a factory.

**Comment by flokixdev** [comment]
Factory can be used for input preprocessing instead. E.g. different number formats that depends on location etc.

**Comment by janbarasek** [comment]
I agree with the removal. We should store the numbers with unlimited precision (as fraction) and pass the rounding parameter at the time of returning from function.
