### ISSUE TITLE
Add tests for Roman numbers

### ISSUE THREAD

**Issue by janbarasek** [mathematicator-core/numbers#14]
I think Roman numbers should contain tests for this cases:

Undefined return:
- `0` (zero)
- `-1`
- `-256`

Big numbers:
- `1000000`
- `54856178844`

**Comment by flokixdev** [comment]
Implemented and tested. For all your inputs it now throws Out of set exception. I know that there exist some technics how to resolve a larger number, however, I am not sure whether to implement it because it is not valid according to original roman numbers set.

**Comment by janbarasek** [comment]
For example `1000000` can be converted to `\overline{M}`.

More info:

- MA: https://mathematicator.com/search/1000000
- Wolfram: https://www.wolframalpha.com/input/?i=1000000+to+roman

Fully works implementation is here: https://github.com/mathematicator-core/calculator/blob/master/src/Numbers/NumberHelper.php#L73

I think this case can be solved in the future, so I keep this issue opened.

**Comment by flokixdev** [comment]
@janbarasek This is one of possible solutions. Another is with brackets: e.g. [M].
Ok, I'll implement it in the way you metioned.
